[package]
name = "service"
version = "0.1.0"
edition = "2021"

[dependencies]
abi = { path = "../abi" }
storage = { path = "../storage" }
tools = { path = "../tools" }

sha2 = { version = "0.10" }
serde = { workspace = true, features = ["derive"] }
