[package]
name = "protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
# grpc
tonic = { workspace = true }
# proto
prost = { workspace = true }
prost-types = { workspace = true }

[build-dependencies]
tonic-build = { workspace = true }
